name: CI - Build & Push

on:
  push:
    branches: [main]
    paths:
      - 'sample-app/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/sample-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        id: tag
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }} ./sample-app
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}

      - name: Update GitOps repo (dev environment)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/argocd-lab-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      - name: Update dev image tag
        run: |
          cd gitops
          cd apps/web-frontend/overlays/dev
          kustomize edit set image ghcr.io/${{ github.repository_owner }}/sample-app=ghcr.io/${{ github.repository_owner }}/sample-app:${{ steps.tag.outputs.TAG }}
          cd ../../../..
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(dev): update sample-app to ${{ steps.tag.outputs.TAG }}"
          git push